name: phpunit

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: ['9.*', '10.*', '11.*', '12.*']
        include:
          - php: 8.1
            laravel: 11.*
            testbench: 9.*
            skip: true
          - php: 8.2
            laravel: 11.*
            testbench: 9.*
          - php: 8.3
            laravel: 11.*
            testbench: 9.*
          - php: 8.1
            laravel: 10.*
            testbench: 8.*
          - php: 8.2
            laravel: 10.*
            testbench: 8.*
          - php: 8.3
            laravel: 10.*
            testbench: 8.*
          - php: 8.1
            laravel: 9.*
            testbench: 7.*
          - php: 8.2
            laravel: 9.*
            testbench: 7.*
          - php: 8.3
            laravel: 9.*
            testbench: 7.*
          - php: '8.2'
            laravel: 12.*
            testbench: 10.*
        exclude:
          - laravel: 12.*
            php: 8.1

    name: PHP${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Update apt
        run: sudo apt-get update --fix-missing

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          if [ "${{ matrix.skip }}" == "true" ]; then
            echo "Skipping Install Dependencies ${{ matrix.php }} with Laravel 11."
            exit 0
          fi
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: |
          if [ "${{ matrix.skip }}" == "true" ]; then
            echo "Skipping Test Execution for ${{ matrix.php }} with Laravel 11."
            exit 0
          fi

          vendor/bin/phpunit --testdox
