name: phpunit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            laravel: 12.*
            testbench: 10.*

          - php: 8.3
            laravel: 12.*
            testbench: 10.*

          - php: 8.4
            laravel: 12.*
            testbench: 10.*

          - php: 8.5
            laravel: 12.*
            testbench: 10.*

          - php: 8.3
            laravel: 13.*
            testbench: 11.*

          - php: 8.4
            laravel: 13.*
            testbench: 11.*

          - php: 8.5
            laravel: 13.*
            testbench: 11.*

    name: PHP${{ matrix.php }} - Laravel ${{ matrix.laravel }}${{ matrix.skip && ' (skipped)' || '' }}


    steps:
      - name: Update apt
        run: sudo apt-get update --fix-missing

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        if: matrix.skip != 'true'
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        if: matrix.skip != 'true'
        run: vendor/bin/phpunit --testdox
